<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\AddCar;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Vios/Alumina Jade/GAU7494 2020
        $car = AddCar::create([
            'vehicle' => 'Sedan',
            'brand' => 'Toyota',
            'model' => 'Vios',
            'year' => '2020',
            'plate' => '',
            'seats' => '5',
            'fuel' => 'Unleaded',
            'displacement' => '',
            'color' => 'Alumina Jade',
            'carlocation' => 'Apas, Cebu City',
            'transmission' => 'Automatic',
            'fname' => 'Marilyn',
            'mname' => 'R.',
            'lname' => 'Balili',
            'email' => 'marzbalskie@gmail.com',
            'phone' => '09127725518',
            'bday' => '1973-08-15',
            'purok' => 'Purok 2',
            'baranggay' => 'Salvador',
            'town' => 'Sierra Bullones',
            'province' => 'Bohol',
            'postal' => '6320',
            'dailyrate' => '1800',
            'weeklyrate' => '11200',
            'monthlyrate' => '32000',
            'carphoto' => 'GAU7494.png',
            'status' => 'Available',
            'is_active' => '1',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        // Vios/Alumina Jade/GAD8768 2020
        $car = AddCar::create([
            'vehicle' => 'Sedan',
            'brand' => 'Toyota',
            'model' => 'Vios',
            'year' => '2020',
            'plate' => '',
            'seats' => '5',
            'fuel' => 'Unleaded',
            'displacement' => '',
            'color' => 'Alumina Jade',
            'carlocation' => 'Apas, Cebu City',
            'transmission' => 'Automatic',
            'fname' => 'Marilyn',
            'mname' => 'R.',
            'lname' => 'Balili',
            'email' => 'marzbalskie@gmail.com',
            'phone' => '09127725518',
            'bday' => '1973-08-15',
            'purok' => 'Purok 2',
            'baranggay' => 'Salvador',
            'town' => 'Sierra Bullones',
            'province' => 'Bohol',
            'postal' => '6320',
            'dailyrate' => '1800',
            'weeklyrate' => '11200',
            'monthlyrate' => '32000',
            'carphoto' => 'GAD8768.png',
            'status' => 'Available',
            'is_active' => '1',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        // Vios/Greyish Blue/GAK2413 2023
        $car = AddCar::create([
            'vehicle' => 'Sedan',
            'brand' => 'Toyota',
            'model' => 'Vios',
            'year' => '2023',
            'plate' => '',
            'seats' => '5',
            'fuel' => 'Unleaded',
            'displacement' => '',
            'color' => 'Greyish Blue',
            'carlocation' => 'Apas, Cebu City',
            'transmission' => 'Automatic',
            'fname' => 'Marilyn',
            'mname' => 'R.',
            'lname' => 'Balili',
            'email' => 'marzbalskie@gmail.com',
            'phone' => '09127725518',
            'bday' => '1973-08-15',
            'purok' => 'Purok 2',
            'baranggay' => 'Salvador',
            'town' => 'Sierra Bullones',
            'province' => 'Bohol',
            'postal' => '6320',
            'dailyrate' => '1800',
            'weeklyrate' => '11200',
            'monthlyrate' => '32000',
            'carphoto' => 'GAK2413.png',
            'status' => 'Available',
            'is_active' => '1',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        // Vios/Alumina Jade/GBC5172 2023
        $car = AddCar::create([
            'vehicle' => 'Sedan',
            'brand' => 'Toyota',
            'model' => 'Vios',
            'year' => '2023',
            'plate' => '',
            'seats' => '5',
            'fuel' => 'Unleaded',
            'displacement' => '',
            'color' => 'Alumina Jade',
            'carlocation' => 'Apas, Cebu City',
            'transmission' => 'Automatic',
            'fname' => 'Marilyn',
            'mname' => 'R.',
            'lname' => 'Balili',
            'email' => 'marzbalskie@gmail.com',
            'phone' => '09127725518',
            'bday' => '1973-08-15',
            'purok' => 'Purok 2',
            'baranggay' => 'Salvador',
            'town' => 'Sierra Bullones',
            'province' => 'Bohol',
            'postal' => '6320',
            'dailyrate' => '1800',
            'weeklyrate' => '11200',
            'monthlyrate' => '32000',
            'carphoto' => 'GBC5172.png',
            'status' => 'Available',
            'is_active' => '1',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        // Vios/Blackish Red/GBE1418 2024
        $car = AddCar::create([
            'vehicle' => 'Sedan',
            'brand' => 'Toyota',
            'model' => 'Vios',
            'year' => '2024',
            'plate' => '',
            'seats' => '5',
            'fuel' => 'Unleaded',
            'displacement' => '',
            'color' => 'Blackish Red',
            'carlocation' => 'Apas, Cebu City',
            'transmission' => 'Automatic',
            'fname' => 'Marilyn',
            'mname' => 'R.',
            'lname' => 'Balili',
            'email' => 'marzbalskie@gmail.com',
            'phone' => '09127725518',
            'bday' => '1973-08-15',
            'purok' => 'Purok 2',
            'baranggay' => 'Salvador',
            'town' => 'Sierra Bullones',
            'province' => 'Bohol',
            'postal' => '6320',
            'dailyrate' => '1800',
            'weeklyrate' => '11200',
            'monthlyrate' => '32000',
            'carphoto' => 'GBE1418.png',
            'status' => 'Available',
            'is_active' => '1',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        // Mirage G4/Metallic Red/HAO664 2024
        $car = AddCar::create([
            'vehicle' => 'Sedan',
            'brand' => 'Toyota',
            'model' => 'Vios',
            'year' => '2024',
            'plate' => '',
            'seats' => '5',
            'fuel' => 'Unleaded',
            'displacement' => '',
            'color' => 'Metallic Red',
            'carlocation' => 'Apas, Cebu City',
            'transmission' => 'Automatic',
            'fname' => 'Marilyn',
            'mname' => 'R.',
            'lname' => 'Balili',
            'email' => 'marzbalskie@gmail.com',
            'phone' => '09127725518',
            'bday' => '1973-08-15',
            'purok' => 'Purok 2',
            'baranggay' => 'Salvador',
            'town' => 'Sierra Bullones',
            'province' => 'Bohol',
            'postal' => '6320',
            'dailyrate' => '1800',
            'weeklyrate' => '11200',
            'monthlyrate' => '32000',
            'carphoto' => 'HAO664.png',
            'status' => 'Available',
            'is_active' => '1',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
}
